steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['ci']
  - name: 'node'
    entrypoint: 'npm'
    args: ['install', 'pkg', '-g']
  - name: 'node'
    entrypoint: 'npm'
    args: ['install', 'typescript', '-g']
